CREATE TABLE teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  description TEXT,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE players (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  description TEXT,
  constitution INT NOT NULL DEFAULT 0,
  strength INT NOT NULL DEFAULT 0,
  intelligence INT NOT NULL DEFAULT 0,
  dexterity INT NOT NULL DEFAULT 0,
  wisdom INT NOT NULL DEFAULT 0,
  charisma INT NOT NULL DEFAULT 0,
  level INT NOT NULL DEFAULT 0,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE players_teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  team_id INT NOT NULL,  
  player_id INT NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (team_id) REFERENCES teams(id),
  FOREIGN KEY (player_id) REFERENCES players(id)
);

----------------------------------

CREATE TABLE badges (
  id INT AUTO_INCREMENT PRIMARY KEY
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
  modified DATETIME DEFAULT CURRENT_TIMESTAMP
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE players_badges (
  id INT AUTO_INCREMENT PRIMARY KEY,
  team_id INT NOT NULL,  
  player_id INT NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (team_id) REFERENCES teams(id),
  FOREIGN KEY (player_id) REFERENCES players(id)
);


CREATE TABLE stat (
  id INT AUTO_INCREMENT PRIMARY KEY
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
  modified DATETIME DEFAULT CURRENT_TIMESTAMP
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stat_entity (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
  modified DATETIME DEFAULT CURRENT_TIMESTAMP
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory (
  id INT AUTO_INCREMENT PRIMARY KEY
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
  modified DATETIME DEFAULT CURRENT_TIMESTAMP
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE match (
  id INT AUTO_INCREMENT PRIMARY KEY
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
  modified DATETIME DEFAULT CURRENT_TIMESTAMP
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE history (
  id INT AUTO_INCREMENT PRIMARY KEY
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
  modified DATETIME DEFAULT CURRENT_TIMESTAMP
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accolades (
  id INT AUTO_INCREMENT PRIMARY KEY
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
  modified DATETIME DEFAULT CURRENT_TIMESTAMP
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accolades_players (
  id INT AUTO_INCREMENT PRIMARY KEY
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
  modified DATETIME DEFAULT CURRENT_TIMESTAMP
  deleted DATETIME DEFAULT CURRENT_TIMESTAMP

  FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE 